### ISSUE TITLE
Create script to extract specific files from any image format

### ISSUE THREAD

**Issue by jarlethorsen** [open-source-dfir/dfvfs-snippets#2]
1. Open a disk image of any format.
2. locate any partitions with a specific filesystem (for example NTFS)
3. Search for a specific file in known path (for example \Windows\System32\config\system)
4. if available, extract file from image

**Comment by joachimmetz** [comment]
The [recursive hasher example script](https://github.com/log2timeline/dfvfs/blob/master/examples/recursive_hasher.py) is a good example here. Also see: https://github.com/log2timeline/dfvfs/wiki/Development

The [VolumeScanner](https://github.com/log2timeline/dfvfs/blob/master/dfvfs/helpers/volume_scanner.py) can help with "1. Open a disk image of any format." and "2. locate any partitions with a specific filesystem (for example NTFS)".

For "3. Search for a specific file in known path (for example \Windows\System32\config\system)" you can use the [FileSystemSearcher](https://github.com/log2timeline/dfvfs/blob/master/dfvfs/helpers/file_system_searcher.py) or recursively iterate the file system. Note that you need to "normalize" the search path depending on the dfVFS files system e.g. the libtsk file system uses `/` for NTFS paths but the libfsntfs (experimental) file system uses `\`.

"4. if available, extract file from image", once you have obtained the file entry you use it to get a FileIO (file-like object) of the data stream. E.g. https://github.com/log2timeline/dfvfs/blob/master/examples/recursive_hasher.py#L52

Also know that plaso [image export](https://github.com/log2timeline/plaso/blob/master/plaso/cli/image_export_tool.py) script provides similar functionality.

**Comment by joachimmetz** [comment]
@jarlethorsen per conversation on the Slack channel a rough outline:

First create a volume scanner mediator, to start with you can use the one provided in dfvfs/helpers/command_line.py:

```
  mediator = command_line.CLIVolumeScannerMediator()
```

Next create a volume scanner provide in dfvfs/helpers/volume_scanner.py:
```
  scanner = volume_scanner.VolumeScanner(mediator=mediator)
```

The volume scanner can also be used as parent class or mix-in of your main class e.g. `FileExtractor`. 

The volume scanner provides the GetBasePathSpecs method that scans for available volumes. The mediator is used provide callback to help get input on how to deal with locked and encrypted volumes or special volumes such as snapshots (VSS).

**Comment by joachimmetz** [comment]
`3. Search for a specific file in known path (for example \Windows\System32\config\system)`

There are multiple ways to go about this:
a. if you have a specific set of paths that you want search for use the file system searcher `FileSystemSearcher` defined in dfvfs/helpers/file_system_searcher.py
b. recursively iterate the file entries in the file system

**Comment by jarlethorsen** [comment]
Thank you for all your guidance so far.

This is my current script (less is more):

```
#!/usr/bin/env python3

from dfvfs.helpers import command_line
from dfvfs.helpers import volume_scanner

image = '/mnt/Diverse/Jarle/testdata/13298323_2017_8088_204_1.E01'
mediator = command_line.CLIVolumeScannerMediator()
scanner = volume_scanner.VolumeScanner(mediator=mediator)
base_path_specs = scanner.GetBasePathSpecs(image)
```

1. How do I force it to process all partitions, and not ask for user input?

2. For disk images with multiple partitions I get hit by a python 2/3 related problem:

```
$ python3 test_dfvfs.py 
The following partitions were found:

Identifier      Offset (in bytes)       Size (in bytes)
p1              32256 (0x00007e00)      78.4MiB / 82.2MB (82220544 B)
p2              82837504 (0x04f00000)   100.0MiB / 104.9MB (104857600 B)
p3              187695104 (0x0b300000)  465.6GiB / 499.9GB (499919093760 B)
Please specify the identifier of the partition that should be
processed. All partitions can be defined as: "all". Note that you can
abort with Ctrl^C.

Partition identifier(s):all
Traceback (most recent call last):
  File "/usr/lib64/python3.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_dfvfs.py", line 9, in <module>
    base_path_specs = scanner.GetBasePathSpecs(image)
  File "/usr/lib/python3.7/site-packages/dfvfs/helpers/volume_scanner.py", line 452, in GetBasePathSpecs
    partition_identifiers = self._GetTSKPartitionIdentifiers(scan_node)
  File "/usr/lib/python3.7/site-packages/dfvfs/helpers/volume_scanner.py", line 182, in _GetTSKPartitionIdentifiers
    volume_system, volume_identifiers)
  File "/usr/lib/python3.7/site-packages/dfvfs/helpers/command_line.py", line 667, in GetPartitionIdentifiers
    selected_volumes = self._ReadSelectedVolumes(volume_system, prefix='p')
  File "/usr/lib/python3.7/site-packages/dfvfs/helpers/command_line.py", line 582, in _ReadSelectedVolumes
    volume_identifiers_string = self._input_reader.Read()
  File "/usr/lib/python3.7/site-packages/dfvfs/helpers/command_line.py", line 76, in Read
    string = codecs.decode(encoded_string, self._encoding, self._errors)
TypeError: decoding with 'UTF-8' codec failed (TypeError: a bytes-like object is required, not 'str')
```

I get the same error when I try running recursive_hasher.py and list_file_entries.py using python3.

**Comment by joachimmetz** [comment]
I'll have a closer look at dfvfs/helpers/command_line.py, this might be a Python 3 compatibility issue in the helper code.

**Comment by joachimmetz** [comment]
@jarlethorsen this is an issue in dfvfs/helpers/command_line.py,, pending fix: https://github.com/log2timeline/dfvfs/pull/378

**Comment by joachimmetz** [comment]
Code has been moved to Python 3 and https://github.com/log2timeline/dfimagetools contains the extract_data_streams script which does something similar with artifact definitions. Closing issue.
